[package]
name = "bake"
version = "0.1.0"
edition = "2021"

[dependencies]
binrw = "0.8.4"
csv = "1.1.6"
hex = { version = "0.4.3", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
